sudo: required
language: elixir
elixir:
  - 1.2.0

services:
  - elasticsearch

before_install:
  - curl -O https://download.elasticsearch.org/elasticsearch/elasticsearch/elasticsearch-2.1.0.deb && sudo dpkg -i --force-confnew elasticsearch-2.1.0.deb

notifications:
  email: false
  slack:
    rooms:
      - zatvobor:eLjCTZD2l85xl19hsSdxkMdN##oss-feed
    on_success: change
